version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/codedeploy-test
permissions:
  - object: <the directory your code will live>
    owner: <user who will deploy your code>
    group: <group that user lives in>
hooks:
  AfterInstall:
    - location: scripts/AfterInstall.sh
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
